---
dependencies:
  - python=3.8.3
  - pandas=1.0.5
  - progress=1.5
  - pip=19.2.3

    pip:
      - pandapower
      - pymongo
      - matplotlib
      - numba
      - lxml
      - django
name: dissertation
